theme = "hugo-photo-theme"
baseurl = ""
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
title = "Hugo Photo Theme"
MetaDataFormat = "toml"
[indexes]
    post = "posts"
    # category = "categories"
    # tag = "tags"
[permalinks]
  post = "/:year/:month/:title/"

[params]

[params.writing]
description = "Writing section description"

[params.header]
feature = "window-cropped"
credit = "Sean Hagen"
creditlink = "https://www.flickr.com/photos/rebelcan/12754943013/in/datetaken-public/"

[params.author]
avatar = ""
name = "Sean Patrick Hagen"
bio = ""

[params.author.social]
twitter = "seanphagen"
youtube = ""
twitch = ""
facebook = ""
linkedin = ""
instagram = ""
tumblr = ""
github = ""
stackoverflow = ""
pinterest = ""
steam = ""
soundcloud = ""
flickr = ""
codepen = ""

[params.author.google]
plus = "SeanPatrickHagen"
analytics = ""