theme = "hugo-photo-theme"
baseurl = ""
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
languageCode = "en-us"
title = "Hugo Photo Theme"
MetaDataFormat = "toml"
[indexes]
    post = "posts"
    # category = "categories"
    # tag = "tags"
[permalinks]
  post = "/:year/:month/:title/"

[params]
    [params.author]
        name = "Sean Patrick Hagen"
    [params.header]
        feature = "window-cropped"
        credit = "Sean Hagen"
        creditlink = "https://www.flickr.com/photos/rebelcan/12754943013/in/datetaken-public/"
